use std::convert::From;
use crate::consts::*;

#[derive(PartialEq, Debug)]
pub enum TelnetOption {
    BinaryTransmission              , // switch to utf-8
    Echo                            , // echo back everything
    Reconnection                    , // support reconnection
    SuppressGoAhead                 ,
    ApproxMessageSizeNegotiation    ,
    Status                          ,
    TimingMark                      ,
    RemoteControlledTransAndEcho    ,
    OutputLineWidth                 ,
    OutputPageSize                  ,
    OutputCarriageReturnDisposition ,
    OutputHorizontalTabStops        ,
    OutputHorizontalTabDisposition  ,
    OutputFormfeedDisposition       ,
    OutputVerticalTabstops          ,
    OutputVerticalTabDisposition    ,
    OutputLinefeedDisposition       ,
    ExtendedASCII                   ,
    Logout                          ,
    ByteMacro                       ,
    DataEntryTerminal               ,
    SUPDUP                          ,
    SUPDUPOutput                    ,
    SendLocation                    ,
    TerminalType                    ,
    EndOfRecord                     ,
    TACACSUserIdentification        ,
    OutputMarking                   ,
    TerminalLocationNumber          ,
    Telnet3270Regime                ,
    X3Pad                           ,
    NegotiateAboutWindowSize        ,
    TerminalSpeed                   ,
    RemoteFlowControl               ,
    Linemode                        ,
    XDisplayLocation                ,
    ExtendedOptionsList             ,
    Other(u8)                       ,
}

impl Into<u8> for TelnetOption {
  fn into(self) -> u8 {
    match self {
      TelnetOption::BinaryTransmission              => BINARY_TRANSMISSION,
      TelnetOption::Echo                            => ECHO,
      TelnetOption::Reconnection                    => RECONNECTION,
      TelnetOption::SuppressGoAhead                 => SUPPRESS_GO_AHEAD,
      TelnetOption::ApproxMessageSizeNegotiation    => APPROX_MESSAGE_SIZE_NEGOTIATION,
      TelnetOption::Status                          => STATUS,
      TelnetOption::TimingMark                      => TIMING_MARK,
      TelnetOption::RemoteControlledTransAndEcho    => REMOTE_CONTROLLED_TRANS_AND_ECHO,
      TelnetOption::OutputLineWidth                 => OUTPUT_LINE_WIDTH,
      TelnetOption::OutputPageSize                  => OUTPUT_PAGE_SIZE,
      TelnetOption::OutputCarriageReturnDisposition => OUTPUT_CARRIAGE_RETURN_DISPOSITION,
      TelnetOption::OutputHorizontalTabStops        => OUTPUT_HORIZONTAL_TAB_STOPS,
      TelnetOption::OutputHorizontalTabDisposition  => OUTPUT_HORIZONTAL_TAB_DISPOSITION,
      TelnetOption::OutputFormfeedDisposition       => OUTPUT_FORM_FEED_DISPOSITION,
      TelnetOption::OutputVerticalTabstops          => OUTPUT_VERTICAL_TAB_STOPS,
      TelnetOption::OutputVerticalTabDisposition    => OUTPUT_VERTICAL_TAB_DISPOSITION,
      TelnetOption::OutputLinefeedDisposition       => OUTPUT_LINE_FEED_DISPOSITION,
      TelnetOption::ExtendedASCII                   => EXTENDED_ASCII,
      TelnetOption::Logout                          => LOGOUT,
      TelnetOption::ByteMacro                       => BYTE_MACRO,
      TelnetOption::DataEntryTerminal               => DATAENTRYTERMINAL,
      TelnetOption::SUPDUP                          => SUPDUP,
      TelnetOption::SUPDUPOutput                    => SUPDUP_OUTPUT,
      TelnetOption::SendLocation                    => SEND_LOCATION,
      TelnetOption::TerminalType                    => TERMINAL_TYPE,
      TelnetOption::EndOfRecord                     => END_OF_RECORD,
      TelnetOption::TACACSUserIdentification        => TACACS_USER_IDENTIFICATION,
      TelnetOption::OutputMarking                   => OUTPUT_MARKING,
      TelnetOption::TerminalLocationNumber          => TERMINAL_LOCATION_NUMBER,
      TelnetOption::Telnet3270Regime                => TELNET_3270_REGIME,
      TelnetOption::X3Pad                           => X3PAD,
      TelnetOption::NegotiateAboutWindowSize        => NEGOTIATE_ABOUT_WINDOW_SIZE,
      TelnetOption::TerminalSpeed                   => TERMINAL_SPEED,
      TelnetOption::RemoteFlowControl               => REMOTE_FLOW_CONTROL,
      TelnetOption::Linemode                        => LINEMODE,
      TelnetOption::XDisplayLocation                => X_DISPLAY_LOCATION,
      TelnetOption::ExtendedOptionsList             => EXTENDED_OPTIONS_LIST,
      TelnetOption::Other(byte)                     => byte,
    }
  }
}

impl From<u8> for TelnetOption {
  fn from(byte: u8) -> TelnetOption {
    match byte {
      BINARY_TRANSMISSION                => TelnetOption::BinaryTransmission,
      ECHO                               => TelnetOption::Echo,
      RECONNECTION                       => TelnetOption::Reconnection,
      SUPPRESS_GO_AHEAD                  => TelnetOption::SuppressGoAhead,
      APPROX_MESSAGE_SIZE_NEGOTIATION    => TelnetOption::ApproxMessageSizeNegotiation,
      STATUS                             => TelnetOption::Status,
      TIMING_MARK                        => TelnetOption::TimingMark,
      REMOTE_CONTROLLED_TRANS_AND_ECHO   => TelnetOption::RemoteControlledTransAndEcho,
      OUTPUT_LINE_WIDTH                  => TelnetOption::OutputLineWidth,
      OUTPUT_PAGE_SIZE                   => TelnetOption::OutputPageSize,
      OUTPUT_CARRIAGE_RETURN_DISPOSITION => TelnetOption::OutputCarriageReturnDisposition,
      OUTPUT_HORIZONTAL_TAB_STOPS        => TelnetOption::OutputHorizontalTabStops,
      OUTPUT_HORIZONTAL_TAB_DISPOSITION  => TelnetOption::OutputHorizontalTabDisposition,
      OUTPUT_FORM_FEED_DISPOSITION       => TelnetOption::OutputFormfeedDisposition,
      OUTPUT_VERTICAL_TAB_STOPS          => TelnetOption::OutputVerticalTabstops,
      OUTPUT_VERTICAL_TAB_DISPOSITION    => TelnetOption::OutputVerticalTabDisposition,
      OUTPUT_LINE_FEED_DISPOSITION       => TelnetOption::OutputLinefeedDisposition,
      EXTENDED_ASCII                     => TelnetOption::ExtendedASCII,
      LOGOUT                             => TelnetOption::Logout,
      BYTE_MACRO                         => TelnetOption::ByteMacro,
      DATAENTRYTERMINAL                  => TelnetOption::DataEntryTerminal,
      SUPDUP                             => TelnetOption::SUPDUP,
      SUPDUP_OUTPUT                      => TelnetOption::SUPDUPOutput,
      SEND_LOCATION                      => TelnetOption::SendLocation,
      TERMINAL_TYPE                      => TelnetOption::TerminalType,
      END_OF_RECORD                      => TelnetOption::EndOfRecord,
      TACACS_USER_IDENTIFICATION         => TelnetOption::TACACSUserIdentification,
      OUTPUT_MARKING                     => TelnetOption::OutputMarking,
      TERMINAL_LOCATION_NUMBER           => TelnetOption::TerminalLocationNumber,
      TELNET_3270_REGIME                 => TelnetOption::Telnet3270Regime,
      X3PAD                              => TelnetOption::X3Pad,
      NEGOTIATE_ABOUT_WINDOW_SIZE        => TelnetOption::NegotiateAboutWindowSize,
      TERMINAL_SPEED                     => TelnetOption::TerminalSpeed,
      REMOTE_FLOW_CONTROL                => TelnetOption::RemoteFlowControl,
      LINEMODE                           => TelnetOption::Linemode,
      X_DISPLAY_LOCATION                 => TelnetOption::XDisplayLocation,
      EXTENDED_OPTIONS_LIST              => TelnetOption::ExtendedOptionsList,
      _                                  => TelnetOption::Other(byte),
    }
  }
}
